// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402150337_AddSubscriptionEntities")]
    partial class AddSubscriptionEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Retailer.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("EmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("email_notifications");

                    b.Property<bool>("InAppNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("in_app_notifications");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("LowStockAlerts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("low_stock_alerts");

                    b.Property<bool>("OrderStatusAlerts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("order_status_alerts");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid")
                        .HasColumnName("retailer_id");

                    b.Property<bool>("SubscriptionAlerts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("subscription_alerts");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_notification_preferences");

                    b.HasIndex("RetailerId")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_preferences_retailer_id");

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Retailer.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CardNumberLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("card_number_last4");

                    b.Property<string>("CardholderNameEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cardholder_name_encrypted");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("ExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_saved");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider_type");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid")
                        .HasColumnName("retailer_id");

                    b.Property<string>("StripePaymentMethodId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_payment_method_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payment_methods");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_payment_methods_expires_at");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("ix_payment_methods_retailer_id");

                    b.HasIndex("RetailerId", "IsDefault")
                        .HasDatabaseName("ix_payment_methods_retailer_default")
                        .HasFilter("is_deleted = false AND is_default = true");

                    b.ToTable("payment_methods", null, t =>
                        {
                            t.HasCheckConstraint("chk_payment_methods_provider_type", "provider_type IN ('Visa', 'Mastercard', 'PayPal', 'ApplePay', 'Stripe', 'GooglePay', 'Bitpay')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Retailer.RetailerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_status");

                    b.Property<string>("BrandLogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("brand_logo_url");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("brand_name");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("google_id");

                    b.Property<bool>("Has3DModels")
                        .HasColumnType("boolean")
                        .HasColumnName("has3d_models");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsRememberMeSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_remember_me_session");

                    b.Property<DateTime?>("LockoutEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_retailer_accounts");

                    b.HasIndex("BrandName")
                        .IsUnique()
                        .HasDatabaseName("ux_retailer_accounts_brand_name_active")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_retailer_accounts_email_active")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("GoogleId")
                        .HasDatabaseName("ix_retailer_accounts_google_id")
                        .HasFilter("google_id IS NOT NULL");

                    b.ToTable("retailer_accounts", null, t =>
                        {
                            t.HasCheckConstraint("chk_retailer_accounts_status", "account_status IN ('Active','PendingEmailVerification','Suspended','PendingDeletion')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Subscriptions.SaasEnquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid")
                        .HasColumnName("retailer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_saas_enquiries");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("ix_saas_enquiries_retailer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_saas_enquiries_status");

                    b.ToTable("saas_enquiries", null, t =>
                        {
                            t.HasCheckConstraint("chk_saas_enquiries_status", "status IN ('Pending','InProgress','Closed')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsRecurringEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_recurring_enabled");

                    b.Property<DateTime?>("PendingDowngradeEffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_downgrade_eff_at");

                    b.Property<Guid?>("PendingDowngradePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_downgrade_plan_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid")
                        .HasColumnName("retailer_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'None'");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("ix_subscriptions_end_date");

                    b.HasIndex("PendingDowngradePlanId")
                        .HasDatabaseName("ix_subscriptions_pending_downgrade_plan_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_subscriptions_plan_id");

                    b.HasIndex("RetailerId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_retailer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_subscriptions_status");

                    b.ToTable("subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("chk_subscriptions_status", "status IN ('None','Trial','Active','PendingDowngrade','Expired','Cancelled')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Subscriptions.SubscriptionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsRecurring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recurring");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PaymentMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_method_id");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end_date");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start_date");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid")
                        .HasColumnName("retailer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_plan_id");

                    b.HasKey("Id")
                        .HasName("pk_subscription_payments");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_subscription_payments_created_at");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_subscription_payments_payment_method_id");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("ix_subscription_payments_retailer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_subscription_payments_status");

                    b.HasIndex("SubscriptionPlanId")
                        .HasDatabaseName("ix_subscription_payments_subscription_plan_id");

                    b.HasIndex("Status", "StripePaymentIntentId")
                        .HasDatabaseName("ix_subscription_payments_status_stripe_intent")
                        .HasFilter("status = 'Completed' AND stripe_payment_intent_id IS NOT NULL");

                    b.ToTable("subscription_payments", null, t =>
                        {
                            t.HasCheckConstraint("chk_subscription_payments_amount", "amount >= 0");

                            t.HasCheckConstraint("chk_subscription_payments_status", "status IN ('Pending','Processing','Completed','Failed','Refunded')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Subscriptions.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("billing_cycle");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<bool>("HasDedicatedTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_dedicated_team");

                    b.Property<bool>("HasSla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_sla");

                    b.Property<bool>("IncludesMobileApps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("includes_mobile_apps");

                    b.Property<bool>("IncludesSourceCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("includes_source_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsWhiteLabel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_white_label");

                    b.Property<int?>("MaxActiveProducts")
                        .HasColumnType("integer")
                        .HasColumnName("max_active_products");

                    b.Property<int?>("MaxMonthlyTryOns")
                        .HasColumnType("integer")
                        .HasColumnName("max_monthly_try_ons");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_amount");

                    b.Property<string>("SupportLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("support_level");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscription_plans");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_subscription_plans_is_active");

                    b.HasIndex("Tier", "BillingCycle")
                        .HasDatabaseName("ix_subscription_plans_tier_billing_cycle");

                    b.ToTable("subscription_plans", null, t =>
                        {
                            t.HasCheckConstraint("chk_subscription_plans_billing_cycle", "billing_cycle IN ('Monthly','Yearly','SaaS')");

                            t.HasCheckConstraint("chk_subscription_plans_commission_rate", "commission_rate >= 0 AND commission_rate <= 1");

                            t.HasCheckConstraint("chk_subscription_plans_price_amount", "price_amount >= 0");

                            t.HasCheckConstraint("chk_subscription_plans_tier", "tier IN ('Basic','Standard','Enterprise','SaaS')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Retailer.NotificationPreference", b =>
                {
                    b.HasOne("Domain.Entities.Retailer.RetailerAccount", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Retailer.NotificationPreference", "RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_preferences_retailer_accounts_retailer_id");
                });

            modelBuilder.Entity("Domain.Entities.Retailer.PaymentMethod", b =>
                {
                    b.HasOne("Domain.Entities.Retailer.RetailerAccount", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_methods_retailer_id");
                });

            modelBuilder.Entity("Domain.Entities.Subscriptions.SaasEnquiry", b =>
                {
                    b.HasOne("Domain.Entities.Retailer.RetailerAccount", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saas_enquiries_retailer_id");
                });

            modelBuilder.Entity("Domain.Entities.Subscriptions.Subscription", b =>
                {
                    b.HasOne("Domain.Entities.Subscriptions.SubscriptionPlan", "PendingDowngradePlan")
                        .WithMany()
                        .HasForeignKey("PendingDowngradePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_subscriptions_pending_downgrade_plan_id");

                    b.HasOne("Domain.Entities.Subscriptions.SubscriptionPlan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_plan_id");

                    b.HasOne("Domain.Entities.Retailer.RetailerAccount", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Subscriptions.Subscription", "RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_retailer_id");

                    b.Navigation("PendingDowngradePlan");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Domain.Entities.Subscriptions.SubscriptionPayment", b =>
                {
                    b.HasOne("Domain.Entities.Retailer.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_subscription_payments_payment_method_id");

                    b.HasOne("Domain.Entities.Retailer.RetailerAccount", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_payments_retailer_id");

                    b.HasOne("Domain.Entities.Subscriptions.SubscriptionPlan", "Plan")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_payments_subscription_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Domain.Entities.Subscriptions.SubscriptionPlan", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
